site_dir: '../siv3d-for-kids.github.io'

# Project information
site_name: Siv3D for Kids
site_description: "" 
site_author: Ryo Suzuki
site_url: https://siv3d-for-kids.github.io/

# Copyright
copyright: Copyright (c) 2018 - present, Ryo Suzuki

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/images/logo.png'
  logo:
    icon: 'tablet'
  palette:
    primary: 'light green'
    accent: 'light green'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ja'
    tokenizer: '[\s　、。，．がのをにへとでやかもる「」『』]+'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/Reputeless'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - kids_styles.css

nav:
  - Siv3D for Kids: index.md
  - イベント日程: events.md
  - 運営メンバー: project.md